version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
    ports:
      - "3306:3306"

  fullstack:
    build: .
    container_name: fullstack
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: todo_app
